### PR TITLE
Fixes #446: Adds save and load feature to the game.

### LINKED ISSUE #446: Add save game feature
### Expected results

Player should be able to save their game state and reload it in the next visit.

### Actual results

No such feature

### Steps to reproduce the issue

Go to the game and play it

## Would you like to work on this

yes, taking it up as part of gci

### PR DESCRIPTION
**Pull request by abishekvashok**
- [x] Read and understood [see CONTRIBUTING.md](https://github.com/fossasia/labyrinth/blob/master/CONTRIBUTING.md)
- [x] Included a preview link and screenshot showing after and before the changes.
- [x] Included a description of change below.
- [x] Squashed the commits.

### Changes done in this Pull Request

- Preview
  
  http://rawgit.com/abishekvashok/labyrinth/master/index.html
- 
  Related Issues or Pull Requests #446 
- Adds save and load feature to the game. Now you can save your badges and
inventory items to local storage. The item will be `stringfy`ied to
create an inline JSON string that will be stored in the local storage.
The stored string data will be then parsed and returned and then
inserted into the player's badges and inventory objects.

Fixes #446 

### My steps to solve it
- Get the badges and inventory items items into a single object
- stringify the object and store it in local storage
- load the json object and parse it
- insert each badge and inventory item back to badges and inventory items.

### Screenshots,
screenshot_20180113_222834

### CODE REVIEW

**Comment by abishekvashok** [comment]
@niccokunzmann done

File: js/save.js [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+function getSaveGame() {
+    var savedObjectJSONString = localStorage.getItem(saveObjectName);
+    var savedObject = JSON.parse(savedObjectJSONString);
+    return savedObject;
+}
+
+function saveGame(player) {
+    var state = new gameState();
+    state.badges = player.badges.items;
+    state.inventory = player.inventory.items;
```
Comment (niccokunzmann) [inline js/save.js]: If you move the lines 34 and 35 into the player, this would be even better. https://en.wikipedia.org/wiki/Law_of_Demeter

File: js/save.js [hunk 2]
```diff
@@ -0,0 +1,51 @@
...
+    saveGameState(state);
+}
+
+function loadGame(player) {
+    if(saveExists() == 1) {
+        var state = getSaveGame();
+        for(var i = 0; i < state.badges.length; i++) {
+            player.badges.add([state.badges[i].name, state.badges[i].image]);
```
Comment (niccokunzmann) [inline js/save.js]: Please also ad lines 41-47 as a function into the player.

**Comment by niccokunzmann** [comment]
The two comments are treated as technical debt. I can merge now.

**Comment by niccokunzmann** [comment]
Thanks!

File: js/save.js (hunk 1 above)
Comment (abishekvashok) [reply js/save.js]: @niccokunzmann you mean like passing something like
```javascript
getItems(state) {
  state.badges = this.badges.items;
}
```

**Comment by niccokunzmann** [comment]
#103

**Comment by abishekvashok** [comment]
@niccokunzmann I could have worked on it though, anyway thanks for the merge.
