### PR TITLE
prevent collision , Fixes #181

### LINKED ISSUE #181: Inventory accepting items twice
### Expected results
- Items should be accepted once ***only***

### Actual results
- Inventory accepts same item multiple times

### Steps to reproduce the issue
- Debug the collision function

## Would you like to work on this
- Yes

### PR DESCRIPTION
**Pull request by YashKumarVerma**
This pull request is related to issue #181  

The problem I want to solve is: that inventory accepts same item twice

My steps to solve it:
Changes: 
- [x] Fix the collision function 

Screenshots/Links:[Deploy/Preview Links: http://rawgit.com/yashkumarverma/labyrinth/inventory/index.html

### CODE REVIEW

File: js/inventory.js [hunk 1]
```diff
@@ -31,8 +31,7 @@ function inventory()
 		};
 
 		// Allow only one item of one name
-		// Collision
-		if(collisionCheck(itemStr,this.itemCollision))
+		if(collisionCheck(itemStr.name,this.itemCollision))
```
Comment (niccokunzmann) [inline js/inventory.js]: It should not be itemStr, then but item.

**Comment by niccokunzmann** [comment]
Thanks!
