### PR TITLE
Fixes #160: Current tile always visible and centered

### LINKED ISSUE #160: Show current tile in the middle of the page
### Expected results

I would like to see the tile when I move through the labyrinth.

### Actual results

Sometimes the tile where I am is hidden behind the GUI or somewhere behind the screen i.e. in 1024x800 resolution.

### Steps to reproduce the issue

Move through the whole labyrinth.
Sometimes, You can not see all the tiles.

Hints:
- You can scroll the page
- You can move the `<div id="tiles"></div>`  to the right and top depending on where you are.

### PR DESCRIPTION
**Pull request by apappu9**
This pull request is related to issue #160 

Changes: 
- The page now scrolls to center the tile containing the player every time the player moves.
- I also moved the data cards to the side to prevent them from overlapping the tiles. I could have shifted the tiles further down instead, but since the inventory card can have an arbitrary height, I thought it would be easier to move the cards rather than moving the tiles every time inventory's height changes.

Preview Link: http://rawgit.com/apappu9/labyrinth/master/index.html

Fixes #160

### CODE REVIEW

**Comment by niccokunzmann** [comment]
@apappu9 Thanks for that pull request! Could you resolve the conflicts? I would like to merge this one. <3

File: js/tiles.js [hunk 1]
```diff
@@ -99,11 +99,24 @@ PlacedTile.prototype.createImage = function(file) {
...
 };
 PlacedTile.prototype.playerLeaves = function(player) {
   this.images.playerLeaves(player);
   this.whenPlayerLeaves(player);
 };
+PlacedTile.prototype.scrollToCenter = function() {
+  const $element = $(this.images.container).children();
+  const offset = $element.offset();
+  // calculate the top and left offsets in order for the tile to be centered
+  const centerTop = window.innerHeight / 2 - 128.157;
```
Comment (niccokunzmann) [inline js/tiles.js]: I think, there are variables for these magic numbers. They should be used.

**Comment by niccokunzmann** [comment]
@apappu9 Somehow, there are more changes.

**Comment by niccokunzmann** [comment]
You did the right thing but we had other changed in the mean time. They were formatting changes so this error is not caused by you but by us editing the files in the mean time again.

File: js/tiles.js (hunk 1 above)
Comment (apappu9) [reply js/tiles.js]: Found the variables. I wasn't sure if they were going to work since they were declared in levels.js which is loaded after tiles.js, but it appears that they do.

**Comment by niccokunzmann** [comment]
Thanks!
